name: CI

on:
  push:
    tags:
      - .*
  
  workflow_dispatch:

jobs:
  lint:
    name: lint the code
    runs-on: ubuntu-latest
    container: massicer/golang_ci
    steps:
      - uses: actions/checkout@v2
      
      - name: lint
        run: make lint
  
  test:
    name: execute the test suite
    runs-on: ubuntu-latest
    container: massicer/golang_ci
    steps:
      - uses: actions/checkout@v2

      - name: execute tests
        run: make test

  build:
    name: Create binary executable
    runs-on: ubuntu-latest
    container: massicer/golang_ci
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make build

  docker:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: massicer/oh-my-gate-iot-executor:${{ env.GITHUB_REF }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
    
